# Generated by Django 3.2 on 2022-09-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220902_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='test',
        ),
    ]
